### ISSUE TITLE
增加下离线阅读吧

### ISSUE THREAD

**Issue by startewho** [ArcEarth/LightNovelClientWindows#1]
UI精美，功能强大。体验也很好，主页滑动还是有点小卡。建议可以把关于那一页单独成页，减小主屏的分屏数。
再增加个离线功能，就完整了

**Comment by ArcEarth** [comment]
谢谢你的支持和意见！离线的功能是在计划中的^_^，因为修bug所以推迟了>_<，接下来一个月内肯定会有的^_^
主页滑动时的卡钝的现象原因是明确的，也会尽快解决的^_^
之后的关于页会升级成“设置”，加入常用的功能的!

再次谢谢您的支持:)
Regards,
Arc Earth
