### ISSUE TITLE
轻之国度未允许第三方APP使用接口

### ISSUE THREAD

**Issue by ugaxm** [ArcEarth/LightNovelClientWindows#2]
轻之国度未允许第三方APP使用接口，请下架此应用。
抓站不道德，请道歉。如有用户信息泄露，请对此负责。

**Comment by ArcEarth** [comment]
应用已下架😊 
非常抱歉未经允许抓了您的数据~
用户信息您不用担心，唯一的漏洞就是网站端的明文登陆了~
