### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by ugaxm** [ArcEarth/LightNovelClientWindows#3]
👍

**Comment by ArcEarth** [comment]
这个应用自您第一次要求以来就没更新过了，也在商店里隐藏了，也道过谦了。相信这还算是合作的态度吧？^_^

Regards,
Arc

**Comment by macroth** [comment]
http://apps.microsoft.com/windows/zh-cn/app/f685715a-305d-4584-ae00-4ff774710331
这叫下（yin）架（cang）？
https://github.com/ArcEarth/LightNovelClientWindows/commit/d358793a9dadc093ee4ff9c4d3d7cb3947b39827
这叫停止更新？

蛋不能乱扯

**Comment by ArcEarth** [comment]
状态请参考截图(邮件附件)^_^WP应用确实是被隐藏的(这意味着用户无法从任何搜索，排行等方式获取应用，我不确定直接链接)，您可以找一部wp验证~
不过W8应用因为只有几十下载量，结果我忘了去隐藏了(两个商店的操作需要分开进行)，非常抱歉，我有Wi-Fi就去搞~

Regards,
Arc

-----Original Message-----
